# Development profile
logging.level.root=INFO
logging.level.kr.co.kfs.asset.oms=DEBUG
logging.level.org.springframework.security=DEBUG
springdoc.swagger-ui.enable=true

oms.cors.allowed-origins=http://localhost:5174,http://admin.localhost:5174,http://127.0.0.1:5174
